version: '3.9'

services:
  api:
    build: ./app
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb://db/users
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - monpay:/data/db


volumes:
    monpay: